services:

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432   # dentro do container, use a porta interna do Postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: oficina
    command: >
      sh -c "npx wait-port db:5432 && npm run start"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oficina
    ports:
      - "5433:5432"  # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: