sonar.projectKey=guilherme-teixeira-gomes_OficinaProjetoFiap
sonar.organization=guilherme-teixeira-gomes
sonar.projectName=oficina-api
sonar.projectVersion=2.0.0

# Diretórios fonte - toda a aplicação
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/*.test.ts,src/application/tests/**,node_modules/**,dist/**,coverage/**

# Diretórios de testes
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

# Cobertura
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts

# Relatório de cobertura
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8

# Host
sonar.host.url=https://sonarcloud.io