sonar.projectKey=oficina-api
sonar.projectName=oficina-api
sonar.projectVersion=1.0.0

# Diretórios fonte
sonar.sources=src
sonar.exclusions=**/*.spec.ts, **/*.test.ts, **/node_modules/**, **/dist/**, **/coverage/**, **/migrations/**

# Diretórios de testes
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts, **/*.test.ts

# Relatório de cobertura
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8

# Configurações adicionais
sonar.organization=oficina-api
sonar.host.url=http://localhost:9000