sonar.projectKey=guilherme-teixeira-gomes_OficinaProjetoFiap
sonar.organization=guilherme-teixeira-gomes
sonar.projectName=oficina-api
sonar.projectVersion=1.0.0

# Diretórios fonte
sonar.sources=src
sonar.exclusions=**/*.spec.ts, **/*.test.ts, **/node_modules/**, **/dist/**, **/coverage/**, **/migrations/**

# Diretórios de testes
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts, **/*.test.ts

# Cobertura - NÃO excluir tudo!
sonar.coverage.exclusions=**/*.spec.ts, **/*.test.ts, **/migrations/**

# Relatório de cobertura
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8

# Host
sonar.host.url=https://sonarcloud.io