apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
data:
  DB_HOST: "postgres-svc"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "oficina"
  NODE_ENV: "production"
  APP_URL: "http://localhost:3000"