apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
type: Opaque
data:
  # Valores em base64
  DB_PASS: cG9zdGdyZXM=        # postgres
  JWT_PASS: c3VwZXJzZWNyZXQ=  # supersecret
  SMTP_USER: b3Jhbjk0QGV0aGVyZWFsLmVtYWls  # oran94@ethereal.email
  SMTP_PASS: WUVkbTZuYTUyN0ZBQ1B4RXlL     # YEdm6na527FACPxEyK