apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
type: Opaque
data:
  # Valores em base64 — SUBSTITUA pelos seus (echo -n "valor" | base64)
  DB_PASS: <base64_da_senha_do_rds>
  JWT_PASS: <base64_do_jwt_secret>
  SMTP_USER: <base64_do_smtp_user>
  SMTP_PASS: <base64_do_smtp_pass>
  NEW_RELIC_LICENSE_KEY: <base64_da_license_key>
